export const ADD_TODO_ITEM = "ADD_TODO_ITEM",
      EDIT_TODO_ITEM = "EDIT_TODO_ITEM",
      REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM",
      EDIT_MODE_ON_CHANGE = "EDIT_MODE_ON_CHANGE",
      CLOSE_EDIT_MODE = "CLOSE_EDIT_MODE",
      TOGGLE_FOR_DONE = "TOGGLE_FOR_DONE";
